sudo: required
language: node_js
compiler: g++

node_js:
  - "0.10"
  - "4"

services:
 - mongodb
 - rabbitmq

before_install:
 - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
 - sudo apt-get update -qq

install:
- sudo apt-get install -qq g++-4.8
- export CXX="g++-4.8"
- npm install

notifications:
  slack:
    rooms:
    - secure: "WpEogHwlr6/Xfre/ofZGN9HaJS1ieXn/bEJZqBRNXj6ENY+Rseh6/5nmtX93xWVpIhCcMjmXMIrS+qdtsmVMCFHawZvfgkRmL/zYc45ZyeLhsaVDAU9CJFKu7XrTHzs9BEAjl6tZcrPI/e7zyssFp5F8YURDeFB1+jDcjyB94xMLIzSsWsKi7n/PRbIfc4ES93WoFbfsezhOtwXfawnv3ToCQNGYDLcgyzpUPI0SY2XNEzCdSm76sQWvwm968/DpMx/+0QPatIYXy/MnVQLfbHwySXLrb0HbkM+b9XLVT0LciZbRGwAYKzKZDlUxnAbNJ3vEfM72jkoue3PMSLbCcgPNi9lrJ54yslx31dsGB1CBJrnmQRrs/Hshj75D0P9B4YgFkDD9bOf7HANMI3HvagH89WG7kK4cfj0Kuccq0/AXXmlKQXZJFSw4K3ApI6nGDfAh3+TgN+ZlzOlUjpblWm/HDmsesNz7irEZzkkVCA5Ha6ZhpJ/yc8lUM9aGzf+u5qJO6owrtLXboMKi4r8Y6AbrxAi7kTuLV7oGumlk1fOB8cMqoyZhODLO4gOQhNFsPkiQ5AwqEGFNOA574IuN09Fm0fylWpe6UJNhy+SYtGLRg5JNjWGd/BFrbVTRlt8KCOXy9ya3Y5+rkBrADzCvirG8L8dqfxZg/S7fZ4DSivw="
